export enum MarchaCarro{
    NEUTRO,PRIMEIRA,SEGUNDA,TERCEIRA,QUARTA,QUINTA,RE
}

export enum MarchaMoto{
    NEUTRO,PRIMEIRA,SEGUNDA,TERCEIRA,QUARTA,QUINTA
}

export enum marchaCaminhao{
    NEUTRO,PRIMEIRA,SEGUNDA,TERCEIRA,QUARTA,QUINTA,SEXTA,SETIMA,OITAVA,RE
}

//let MarchaMoto1: MarchaMoto = MarchaMoto.